### ISSUE TITLE
Invalid base64 secret key encoding

### ISSUE THREAD

**Issue by Ypnose** [chneukirchen/outils#2]
Hi chris2,
Trying to verify file(s) (or even sign) with <code>signify</code> fails with the following message:

```
signify: invalid base64 encoding in foo.sec
```

_**How to reproduce:**_
Generate a new key pair:

```
signify -G -c 'foo pair' -p foo.pub -s foo.sec
```

Create a random file:

```
echo "foobarbaz" >file.txt
```

Get checksums to a file:

```
sha256sum --tag file.txt >sha.txt
```

Embed the signature in a new <code>sha.sig</code> file:

```
signify -S -e -s foo.sec -m sha.txt -x sha.sig
```

It returns the above error. I do not know if it belongs to upstream or not. <code>signify</code> was statically built with libressl <code>2.3.3</code>, GCC <code>5.3.0</code> and musl <code>1.1.14</code>.
**EDIT:** Tested with OpenBSD 5.9 and it does not happen.

**Comment by leahneukirchen** [comment]
Ok, my standalone signify can read the key, so generation is ok it seems... let's see whats going on there.

**Comment by leahneukirchen** [comment]
Looks like this is because this old version of base64.c has an off by one -.-

**Comment by Ypnose** [comment]
I'll test that tomorrow, but I sincerely thank you for the valuable help. :)
